### ISSUE TITLE
Help us with HLGtoSDR shader, please

### ISSUE THREAD

**Issue by opg1212** [haasn/blog#4]
Good day, Niklas
I'm novice on github.com so sorry I don't find place where ask you personally so I decided write to your blog - I guess you (or may be I) can remove this record in a future. Am I right?
Watching on https://github.com/haasn/colour I guess you're strong in colors and in mpv.
Since I wrote https://forum.doom9.org/showthread.php?t=176909 until now I haven't any real answer there about HLGtoSDR (if I don't mistake ARIB STD-B67 to BT.709) HLSL (not GLSL) pixel shader (ps_2_0 or ps_3_0 is supported in WindowsXP-10 freeware SAT receiving program SmartDVB with EVR Custom presenter was taken from MPC-BE with one of its developer agreement).
I can't find any working well enough like in mpv-x86_64-20190714-git-65b1c2d.7z 2019-07-14 and  ~ an year earlier I tried (mpv-x86_64-20190804-git-69c93b6.7z 2019-08-04 and later gave more pink instead of red when software (in hardware they are equal but when I tried latest mpv-x86_64-20200614-git-c7fe4ae.7z red is pink in both software and hardware) decoding even if colors are brighter - I want see darker but Ferrari - btw I'm Lewis Hamilton and Mersedes Formula1 fan - must be red but not pink) until now (((
I'm not pixel-shader programmer (and I don't have any friend with that skill), moreover I'm not programmer at all so can you help us (SAT on computers amateurs) with HLGtoSDR shader (or my be know who can help) we can freely use in app SmartDVB to watch HLG SAT channels directly from SATs with ~ right colors live on SDR monitors? Btw my e-mail victorls@ya.ru
PS. https://haasn.xyz/posts/2020-06-20-positive-and-negative-fairness.html is very interesting.
Best regards
Victor

**Comment by haasn** [comment]
I'm not really sure what you're asking. But if you want shaders for HDR->SDR tonemapping, either [use libplacebo](https://code.videolan.org/videolan/libplacebo/-/blob/master/src/shaders/colorspace.c#L819) or copy its code (license is LGPLv2.1+). I'm not sure there's much else I can offer because it's not clear to me what the issue is.
